source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MessagesUIKit_Example' do
  pod "MessagesUIKit", :path => "../"
end

target 'MessagesUIKit_Tests' do
  pod "MessagesUIKit", :path => "../"

  
end
